version: '3'
services:
  fastapi:
    image: fastapi-model-server:v1.0
    ports:
      - "8000:8000"
    networks:
      - my_network

  streamlit:
    image: streamlit-app:v1.0
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://fastapi:8000
    networks:
      - my_network

networks:
  my_network:
