apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: streamlit-app:v1.1  # Replace with your Docker image
        ports:
        - containerPort: 8501  # The port your Streamlit app listens on
